version: "3.8"

services:
  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    ports:
      - "5021:8040"

  product-service:
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile
    ports:
      - "5022:8040"

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    ports:
      - "5023:8040"

  payment-service:
    build:
      context: .
      dockerfile: src/PaymentService/Dockerfile
    ports:
      - "5024:8040"
