version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # AMQP - RabbitMQ Port
      - "15672:15672" # UI - RabbitMQ Management Port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
    networks:
      - app_network

  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    ports:
      - "5021:8040"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user-service:8040/api/users/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s

  product-service:
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile
    ports:
      - "5022:8040"
    networks:
      - app_network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://product-service:8040/api/products/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    ports:
      - "5023:8040"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://order-service:8040/api/orders/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s

  payment-service:
    build:
      context: .
      dockerfile: src/PaymentService/Dockerfile
    ports:
      - "5024:8040"
    networks:
      - app_network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://payment-service:8040/api/payments/health"]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s

networks:
  app_network:
    driver: bridge
